### PR TITLE
[SCB-365]when configured ssl certificates not exists, startup will hang and no error messages

### PR DESCRIPTION
**Pull request by liubao68**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean install` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by wujimin** [comment]
maybe there is something not confirmed.
in my test, there is no problem.  throw exception directly or throw from future, both got the same result.
so maybe this is not the root cause.

image

**Comment by liubao68** [comment]
Please see issues description. In your demo, should include HttpServer or HttpClient setUp， otherwise no CloseHook is registered and vert.x works fine.  Or you can run SpringMVCServer deom, and configure make DemoSSLScutom to return wrong path and this will happen.

**Comment by wujimin** [comment]
submit a vertx issue, waiting for response.

**Comment by liubao68** [comment]
@wujimin can you provide issue link? And I think this modification have no side effect and can be merged before vert.x fixed the problem.

**Comment by wujimin** [comment]
https://github.com/eclipse/vert.x/issues/2331

already closed, vertx team did not know what happened for this issue, still try to discuss

**Comment by liubao68** [comment]
It seems vert.x is not going to handle this, can we merge this PR to fix the problem ?

**Pull request merged**
