### PR TITLE
[SCB-176] Generate traceId

### PR DESCRIPTION
**Pull request by yhs0092**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

See details in [https://issues.apache.org/jira/browse/SCB-176](https://issues.apache.org/jira/browse/SCB-176).
- provide a traceId generator
- provide a HttpServerFilter:
  + if header contains traceId, move it into invocation context
  + if invocation context carries traceId, let it go
  + if http header and invocation context don't contain traceId, generate a traceId and set into invocation context
- use "X-B3-TraceId" as the header name of traceId, since this is the default traceId header name of zipkin.

### CODE REVIEW

**Comment by WillemJiang** [comment]
Just a quick question, what's the relationship between this change and the old zipkin tracing code.
AFAIK,  ZipkinTracingHandler of Java Chassis can take care the creation of SpanID, and it should take care of the TraceID at the same time.  Can you double check it?

**Comment by wujimin** [comment]
we always generate traceId, trace solution will based on this
please ensure zipkin no problem, then  i will  approve this  PR

**Comment by WillemJiang** [comment]
@seanyinx Could you take a look at this PR?

**Comment by yhs0092** [comment]
I've taken an exam on the situation when users enable our ZipkinTracingHandler to use open zipkin. 
In current solution, the traceId generated by TracingFilter will be ignored by the inner logic of Brave, and a new span will be generated. The traceId transported in the invocation chain is the one that Brave generates. And the function of zipkin tracing works normally.

**Pull request merged**
