### PR TITLE
SCB-314 support custom rest transport server compress and max header …

### PR DESCRIPTION
**Pull request by jeho0815**
…size

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean install` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by wujimin** [comment]
what's the solution for servlet rest?

**Comment by jeho0815** [comment]
@wujimin  use J2EE container to do this，like tomcat connector has config compression="on"

**Comment by wujimin** [comment]
because we add some configuration
is it possible make it work directly in web container?

**Comment by jeho0815** [comment]
I think we can't do this now, Tomcat use the connector, Jetty use gzipFilter, they are not a standard implement

**Comment by wujimin** [comment]
ok
then maybe need to write the difference in the document?

**Comment by jeho0815** [comment]
use pull request https://github.com/apache/incubator-servicecomb-java-chassis/pull/541

**Pull request closed without merging**
